# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install gRPC
      run: |
            go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
            go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

    - name: make grpc codes
      run: make gen-proto

    - name: Install dependencies
      run: go mod tidy

    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
            rm -rf dist
            mkdir dist
            go build -o dist/memoapp-server ./main.go
            go build -o dist/memoapp-client ./client/main.go

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        path: dist
